### ISSUE TITLE
Switch to new Inco testnet "Gentry"

### ISSUE THREAD

**Issue by amaury1093** [0xAkrasia/In-Theory-Games#1]
Hey @0xAkrasia, I see the current dapp points to the Inco devnet https://evm-rpc.inco.network/.

We're working on a new testnet, called "Gentry", based on a newer version of go-ethereum (allows post-Shanghai contracts), it's currently live since a couple of days ago at https://testnet.inco.org, chain-id is still 9090, faucet is `curl -X POST https://faucet.testnet.inco.org/api/get-faucet -H "Content-Type: application/json" -d '{"address": "Your Address"}'`.

If you want to test to the new testnet, there are a couple of changes to make, most notably update fhevmjs. I updated Inco's react template in this PR https://github.com/Inco-fhevm/fhevmjs-react-example/pull/2, you can take a look at the diff.

I'm updating docs.inco.network to reflect these changed. Happy to help in the meantime if you have any issues.

**Comment by 0xAkrasia** [comment]
Thanks for sharing! The latest update is deployed to testnet and includes updates to associated code in the front end.
